typography_spectrum: 1
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#0f683a'
    - '#2e2e2e'
    - '#bcbcbc'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.49121
analytics:
  google: UA-28806933-3
  facebook: null
  twitter: null
name: ShipElectronic
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: ShipElectronic
description: removing age from older ship automation
purpose: []
