name: ShipElectronic
favicon: null
layout_spectrum: 0.018682808382436633
typography_spectrum: 0.76746268523857
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.23780403682030737
  lightness: 0.5
  saturation: 0.1399739533662796
  rhythmicContrast: 0.5
purpose: []
